# Starship prompt - Solarized Light

add_newline = true
command_timeout = 500

format = """$directory$git_branch$git_status$python$nodejs$java$cmd_duration
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
style = "yellow bold"
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = ""
style = "green"
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "green"

[python]
symbol = ""
format = '[$symbol$virtualenv]($style) '
style = "blue"

[nodejs]
symbol = ""
format = "[$symbol$version]($style) "
style = "green"

[java]
symbol = ""
format = "[$symbol$version]($style) "
style = "red"
detect_files = ["pom.xml", "build.gradle", "deps.edn", "project.clj"]

[cmd_duration]
min_time = 2000
format = "[$duration](yellow) "
